/**
 * Student Routes Metadata - بيانات مسارات الطالب
 *
 * Metadata للمسارات الخاصة بالطلاب (Dashboard, Lessons, Assessments, Projects, Storage)
 */

import { RouteMetadata } from '../../types'
import { ROUTES } from '@/domain/constants/routes.constants'
import { LayoutDashboard, BookOpen, Cloud, FileText, FolderKanban } from 'lucide-react'

export const studentMetadata: Record<string, RouteMetadata> = {
  [ROUTES.DASHBOARD]: {
    title: 'لوحة التحكم',
    description: 'لوحة التحكم الرئيسية',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.dashboard',
    icon: LayoutDashboard,
    layout: 'main',
    showInNav: true,
    navOrder: 2,
    analytics: {
      category: 'Navigation',
      action: 'View Dashboard',
    },
  },
  [ROUTES.LESSONS]: {
    title: 'الدروس',
    description: 'استكشف جميع الدروس',
    requiresAuth: true,
    requiredPermissions: ['lessons.view'],
    breadcrumb: 'breadcrumbs.lessons',
    icon: BookOpen,
    layout: 'main',
    showInNav: true,
    navOrder: 3,
    analytics: {
      category: 'Learning',
      action: 'View Lessons',
    },
  },
  [ROUTES.LESSON_DETAIL_PATTERN]: {
    title: 'تفاصيل الدرس',
    description: 'تفاصيل الدرس',
    requiresAuth: true,
    requiredPermissions: ['lessons.view'],
    breadcrumb: 'breadcrumbs.lesson_details',
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ASSESSMENTS]: {
    title: 'التقييمات',
    description: 'استكشف جميع التقييمات المتاحة',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.assessments',
    icon: FileText,
    layout: 'main',
    showInNav: true,
    navOrder: 3,
  },
  [ROUTES.ASSESSMENT_DETAIL_PATTERN]: {
    title: 'تفاصيل التقييم',
    description: 'عرض تفاصيل التقييم',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.assessment_details',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ASSESSMENT_TAKE_PATTERN]: {
    title: 'حل التقييم',
    description: 'حل التقييم التعليمي',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.solve_assessment',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ASSESSMENT_RESULTS_PATTERN]: {
    title: 'نتائج التقييم',
    description: 'عرض نتائج التقييم',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.assessment_results',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ASSESSMENT_NEW]: {
    title: 'تقييم جديد',
    description: 'إنشاء تقييم تعليمي جديد',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.new_assessment',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ASSESSMENT_FORM_PATTERN]: {
    title: 'تعديل التقييم',
    description: 'تعديل التقييم التعليمي',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.edit_assessment',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.PROJECTS]: {
    title: 'المشاريع',
    description: 'استكشف جميع المشاريع التعليمية',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.projects',
    icon: FolderKanban,
    layout: 'main',
    showInNav: true,
    navOrder: 4,
  },
  [ROUTES.PROJECT_DETAIL_PATTERN]: {
    title: 'تفاصيل المشروع',
    description: 'عرض تفاصيل المشروع التعليمي',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.project_details',
    icon: FolderKanban,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.PROJECT_NEW]: {
    title: 'مشروع جديد',
    description: 'إنشاء مشروع تعليمي جديد',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.new_project',
    icon: FolderKanban,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.PROJECT_FORM_PATTERN]: {
    title: 'تعديل المشروع',
    description: 'تعديل المشروع التعليمي',
    requiresAuth: true,
    breadcrumb: 'breadcrumbs.edit_project',
    icon: FolderKanban,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.STORAGE]: {
    title: 'التخزين السحابي',
    description: 'إدارة ملفاتك السحابية',
    requiresAuth: true,
    requiredPermissions: ['storage.view'],
    breadcrumb: 'breadcrumbs.storage',
    icon: Cloud,
    layout: 'main',
    showInNav: true,
    navOrder: 4,
    analytics: {
      category: 'Storage',
      action: 'View Storage',
    },
  },
  [ROUTES.STORAGE_BROWSER_PATTERN]: {
    title: 'متصفح التخزين',
    description: 'تصفح ملفاتك',
    requiresAuth: true,
    requiredPermissions: ['storage.view'],
    breadcrumb: 'breadcrumbs.storage_browser',
    layout: 'main',
    showInNav: false,
  },
}
