/**
 * Admin Routes Metadata - بيانات مسارات المسؤول
 *
 * Metadata للمسارات الخاصة بالمسؤولين
 */

import { RouteMetadata } from '../../types'
import { ROUTES } from '@/domain/constants/routes.constants'
import {
  Shield,
  Users,
  Settings,
  FileText,
  Globe,
  AlertTriangle,
  Activity,
  Database,
  BarChart,
  Network,
  HardDrive,
  Code,
  GitBranch,
  ShieldCheck,
} from 'lucide-react'

export const adminMetadata: Record<string, RouteMetadata> = {
  [ROUTES.ADMIN_DASHBOARD]: {
    title: 'لوحة تحكم المسؤول',
    description: 'إدارة شاملة للنظام والمستخدمين',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'لوحة تحكم المسؤول',
    icon: Shield,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Admin Dashboard',
    },
  },
  [ROUTES.ADMIN_USERS]: {
    title: 'إدارة المستخدمين',
    description: 'إدارة المستخدمين و والأدوار',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'إدارة المستخدمين',
    icon: Users,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Users Management',
    },
  },
  [ROUTES.ADMIN_WHITELIST]: {
    title: 'إدارة القائمة البيضاء',
    description: 'إدارة  المتقدمة للمستخدمين المصرح لهم',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['whitelist.manage'],
    breadcrumb: 'إدارة القائمة البيضاء',
    icon: ShieldCheck,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Whitelist Management',
    },
  },
  [ROUTES.ADMIN_SECURITY_DASHBOARD]: {
    title: 'لوحة تحكم الأمان',
    description: 'مراقبة وإدارة الأمان في النظام',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'لوحة تحكم الأمان',
    icon: Shield,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Security Dashboard',
    },
  },
  [ROUTES.ADMIN_SECURITY_SESSIONS]: {
    title: 'إدارة الجلسات',
    description: 'عرض وإدارة جميع الجلسات النشطة',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'إدارة الجلسات',
    icon: Users,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ADMIN_SECURITY_LOGS]: {
    title: 'سجلات الأمان',
    description: 'تتبع ومراقبة جميع الأحداث الأمنية',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'سجلات الأمان',
    icon: FileText,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ADMIN_SECURITY_SETTINGS]: {
    title: 'إعدادات الأمان',
    description: 'تكوين سياسات الأمان والمصادقة',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'إعدادات الأمان',
    icon: Settings,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ADMIN_SECURITY_ROUTES]: {
    title: 'حماية المسارات',
    description: 'إدارة قواعد حماية المسارات و',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'حماية المسارات',
    icon: Globe,
    layout: 'main',
    showInNav: false,
  },
  [ROUTES.ADMIN_ANALYTICS_ERRORS]: {
    title: 'لوحة تحكم الأخطاء',
    description: 'عرض وتحليل الأخطاء في النظام',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'لوحة تحكم الأخطاء',
    icon: AlertTriangle,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Error Dashboard',
    },
  },
  [ROUTES.ADMIN_ANALYTICS_PERFORMANCE]: {
    title: 'لوحة تحكم الأداء',
    description: 'عرض وتحليل مقاييس الأداء في النظام',
    requiresAuth: true,
    requiredRole: 'admin',
    breadcrumb: 'لوحة تحكم الأداء',
    icon: Activity,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Performance Dashboard',
    },
  },
  [ROUTES.DEVELOPER_DASHBOARD]: {
    title: 'لوحة تحكم المطور',
    description: 'أدوات وإحصائيات متخصصة للمطورين',
    requiresAuth: true,
    requiredRole: 'developer',
    breadcrumb: 'لوحة تحكم المطور',
    icon: Shield,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Developer',
      action: 'View Developer Dashboard',
    },
  },
  [ROUTES.DEVELOPER_SECURITY_ANALYTICS]: {
    title: 'تحليلات الأمان',
    description: 'تحليل متقدم للأمان والأنماط',
    requiresAuth: true,
    requiredRole: 'developer',
    breadcrumb: 'تحليلات الأمان',
    icon: Shield,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Developer',
      action: 'View Security Analytics',
    },
  },
  [ROUTES.DEVELOPER_SECURITY_MONITORING]: {
    title: 'مراقبة الأمان',
    description: 'مراقبة النظام في الوقت الفعلي',
    requiresAuth: true,
    requiredRole: 'developer',
    breadcrumb: 'مراقبة الأمان',
    icon: Shield,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Developer',
      action: 'View Security Monitoring',
    },
  },
  // Database Core Routes
  [ROUTES.ADMIN_DATABASE_CORE_DASHBOARD]: {
    title: 'لوحة تحكم Database Core',
    description: 'مراقبة وإدارة قاعدة البيانات بشكل شامل',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.view'],
    breadcrumb: 'Database Core',
    icon: Database,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Database Core Dashboard',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_PERFORMANCE]: {
    title: 'مراقبة الأداء',
    description: 'مراقبة وتحليل أداء قاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.metrics.view'],
    breadcrumb: 'مراقبة الأداء',
    icon: BarChart,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Performance Monitoring',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_CONNECTIONS]: {
    title: 'إدارة الاتصالات',
    description: 'إدارة ومراقبة اتصالات قاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.connections.manage'],
    breadcrumb: 'إدارة الاتصالات',
    icon: Network,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Connections Management',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_CACHE]: {
    title: 'إدارة Cache',
    description: 'مراقبة وإدارة Cache',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.cache.manage'],
    breadcrumb: 'إدارة Cache',
    icon: HardDrive,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Cache Management',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_EXPLORER]: {
    title: 'Database Explorer',
    description: 'استكشف الجداول والبيانات في قاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.explore'],
    breadcrumb: 'Database Explorer',
    icon: Database,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Database Explorer',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_QUERY_BUILDER]: {
    title: 'Query Builder',
    description: 'بناء وتنفيذ الاستعلامات SQL',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.query.execute'],
    breadcrumb: 'Query Builder',
    icon: Code,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Query Builder',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_TRANSACTIONS]: {
    title: 'مراقبة المعاملات',
    description: 'مراقبة وتحليل المعاملات في قاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.transactions.view'],
    breadcrumb: 'مراقبة المعاملات',
    icon: Activity,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Transactions Monitoring',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_AUDIT]: {
    title: 'Audit Logs',
    description: 'سجل العمليات والأنشطة في قاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.audit.view'],
    breadcrumb: 'Audit Logs',
    icon: FileText,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Audit Logs',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_BACKUPS]: {
    title: 'إدارة النسخ الاحتياطي',
    description: 'إدارة النسخ الاحتياطي لقاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.backups.manage'],
    breadcrumb: 'إدارة النسخ الاحتياطي',
    icon: Database,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Backup Management',
    },
  },
  [ROUTES.ADMIN_DATABASE_CORE_MIGRATIONS]: {
    title: 'إدارة Migrations',
    description: 'إدارة Migrations لقاعدة البيانات',
    requiresAuth: true,
    requiredRole: 'admin',
    requiredPermissions: ['database-core.migrations.manage'],
    breadcrumb: 'إدارة Migrations',
    icon: GitBranch,
    layout: 'main',
    showInNav: false,
    analytics: {
      category: 'Admin',
      action: 'View Migrations Management',
    },
  },
}
